version: '3.8'

services:
  backend:
    build:
      context: ./MaVille - prototype 2/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./MaVille - prototype 2/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"